---
- name: Configurar LAMP en Servidores
  hosts: linux
  become: yes

  vars_files:
    - vars.yaml

  tasks:
    - name: Preparar Servidores
      apt:
        update_cache: yes
        name:
          - sudo
          - ufw
        state: present

    - name: Instalar Apache
      apt:
        name: apache2
        state: present
      register: apache

    - name: Permitir trafico HTTP/HTTPS
      ufw:
        rule: allow
        name: "WWW Full"
      when: apache.changed
      notify: Reiniciar Apache

    - name: Instalar MariaDB
      apt:
        name: mariadb-server
        state: present
      register: mariadb

    - name: Configurar MariaDB
      shell: >
        echo -e "\n\nn\nn\ny\ny\ny\ny" | mysql_secure_installation
      when: mariadb.changed

    - name: Instalar PHP
      apt:
        name: "{{item}}"
        state: present
      loop:
        - php
        - libapache2-mod-php
        - php-mysql
      notify: Reiniciar Apache

    - name: Crear Carpeta para Dominio
      file:
        path: "/var/www/{{dominio}}"
        state: directory
      register: carpeta

    - name: Asignar Permisos a Carpeta
      file:
        path: "/var/www/{{dominio}}"
        state: directory
        owner: "{{usuario}}"
        group: "{{usuario}}"
        recurse: yes
      when: carpeta.changed
      notify: Reiniciar Apache

    - name: Crear Archivo de Configuracion
      template:
        src: /home/alexvilla/.ansible/templates/vhost.cfg
        dest: "/etc/apache2/sites-available/{{dominio}}.conf"
      register: archivo

    - name: Habilitar Nuevo VirtualHost
      command: a2ensite {{dominio}}
      when: archivo.changed

    - name: Deshabilitar Sitio Predeterminado de Apache
      file:
        path: "/etc/apache2/sites-available/000-default.conf"
        state: absent
      when: archivo.changed
      notify: Reiniciar Apache

  handlers:
    - name: Reiniciar Apache
      systemd:
        name: apache2
        state: restarted
